CONTROL_DT = 0.05
DISPLAY_WIDTH = 1280
DISPLAY_HEIGHT = 720

AUTO_ROUTE_SHAPE = "auto"
AUTO_MAP_NAME = "auto"
CURRENT_MAP_NAME = "current"

SUPPORTED_MAPS = (
    "Town01",
    "Town01_Opt",
    "Town02",
    "Town02_Opt",
    "Town03",
    "Town03_Opt",
    "Town04",
    "Town04_Opt",
    "Town05",
    "Town05_Opt",
    "Town10HD",
    "Town10HD_Opt",
)

ROUTE_SHAPE_MAP_PREFERENCES = {
    "true_straight": ("Town04", "Town04_Opt", "Town05", "Town05_Opt"),
    "straight": ("Town04", "Town04_Opt", "Town05", "Town05_Opt", "Town10HD", "Town10HD_Opt"),
    "gentle_curve": ("Town03", "Town03_Opt", "Town10HD", "Town10HD_Opt", "Town05", "Town05_Opt"),
    "s_curve": ("Town03", "Town03_Opt", "Town05", "Town05_Opt", "Town10HD", "Town10HD_Opt"),
    "curvy": ("Town05", "Town05_Opt", "Town03", "Town03_Opt", "Town10HD", "Town10HD_Opt"),
}

MAP_ROUTE_PROFILES = {
    "Town01": {
        "speed_bands": ("low", "medium"),
        "length_scale": 0.85,
        "min_auto_length_m": 900.0,
        "max_auto_length_m": 1800.0,
    },
    "Town02": {
        "speed_bands": ("low", "medium"),
        "length_scale": 0.85,
        "min_auto_length_m": 900.0,
        "max_auto_length_m": 1800.0,
    },
    "Town03": {
        "speed_bands": ("low", "medium", "high"),
        "length_scale": 1.00,
        "min_auto_length_m": 1100.0,
        "max_auto_length_m": 2500.0,
    },
    "Town04": {
        "speed_bands": ("high", "very_high"),
        "length_scale": 1.15,
        "min_auto_length_m": 1500.0,
        "max_auto_length_m": 3600.0,
    },
    "Town05": {
        "speed_bands": ("low", "medium", "high", "very_high"),
        "length_scale": 1.10,
        "min_auto_length_m": 1200.0,
        "max_auto_length_m": 3400.0,
    },
    "Town10HD": {
        "speed_bands": ("medium", "high", "very_high"),
        "length_scale": 1.15,
        "min_auto_length_m": 1500.0,
        "max_auto_length_m": 3600.0,
    },
}

CONTROLLER_SPEED_LIMIT_PROFILES = {
    "pid": {
        "min_turn_speed_scale": 1.00,
        "recovery_min_speed_scale": 1.00,
        "emergency_turn_speed_scale": 1.00,
        "max_lateral_accel_scale": 0.94,
        "entry_max_speed_scale": 1.00,
        "entry_curvature_threshold_scale": 0.95,
        "entry_full_cap_curvature_scale": 1.02,
        "lateral_error_scale": 1.00,
        "heading_error_scale": 1.00,
        "lateral_error_rate_scale": 1.10,
        "heading_error_rate_scale": 1.10,
    },
    "lqr": {
        "min_turn_speed_scale": 0.90,
        "recovery_min_speed_scale": 0.78,
        "emergency_turn_speed_scale": 0.82,
        "max_lateral_accel_scale": 0.96,
        "entry_max_speed_scale": 0.98,
        "entry_curvature_threshold_scale": 0.88,
        "entry_full_cap_curvature_scale": 0.95,
        "lateral_error_scale": 0.90,
        "heading_error_scale": 0.95,
        "lateral_error_rate_scale": 0.96,
        "heading_error_rate_scale": 1.00,
    },
    "mpc": {
        "min_turn_speed_scale": 0.92,
        "recovery_min_speed_scale": 0.78,
        "emergency_turn_speed_scale": 0.80,
        "max_lateral_accel_scale": 0.70,
        "entry_max_speed_scale": 0.86,
        "entry_curvature_threshold_scale": 0.75,
        "entry_full_cap_curvature_scale": 0.70,
        "lateral_error_scale": 0.72,
        "heading_error_scale": 0.76,
        "lateral_error_rate_scale": 0.74,
        "heading_error_rate_scale": 0.76,
    },
}

DEFAULTS = {
    "target_speed": 70.0,
    "planner_mode": "frenet",
    "planner_fallback": "legacy",
    "planner_validation_spacing": 0.25,
    "planner_vehicle_half_width": 1.05,
    "planner_lane_margin": 0.35,
    "planner_topology_beam_width": 24,
    "planner_lateral_beam_width": 64,
    "planner_candidate_cap": 512,
    "planner_deadline": 5.0,
    "planner_max_curvature": 0.20,
    "planner_max_curvature_rate": 0.020,
    "planner_max_lateral_accel": 6.5,
    "planner_max_lateral_jerk": 10.0,
    "tracker_max_rollback": 2.0,
    "tracker_hold_steps": 3,
    "carla_host": "localhost",
    "carla_port": 2000,
    "carla_timeout": 20.0,
    "speed_planner_mode": "adaptive",
    "speed_planner_limit_profile": "controller",
    "route_resolution": 1.0,
    "look_ahead": 10.0,
    "speed_planner_min_turn_speed": 48.0,
    "speed_planner_recovery_min_speed": 40.0,
    "speed_planner_max_lateral_accel": 18.0,
    "speed_planner_max_accel": 3.5,
    "speed_planner_max_decel": 9.0,
    "speed_planner_lateral_error_warning": 1.6,
    "speed_planner_lateral_error_critical": 2.6,
    "speed_planner_heading_error_warning": 12.0,
    "speed_planner_heading_error_critical": 18.0,
    "speed_planner_lateral_error_rate_warning": 0.8,
    "speed_planner_lateral_error_rate_critical": 1.6,
    "speed_planner_heading_error_rate_warning": 8.0,
    "speed_planner_heading_error_rate_critical": 16.0,
    "speed_planner_lateral_error_rate_activation": 0.8,
    "speed_planner_heading_error_rate_activation": 8.0,
    "speed_planner_error_rate_alpha": 0.25,
    "speed_planner_recovery_hold_steps": 3,
    "speed_planner_entry_max_speed": 70.0,
    "speed_planner_entry_curvature_threshold": 0.015,
    "speed_planner_entry_full_cap_curvature": 0.03,
    "speed_planner_emergency_turn_speed": 36.0,
    "speed_planner_emergency_curvature_threshold": 0.08,
    "speed_planner_emergency_full_cap_curvature": 0.12,
    "collision_zero_speed_timeout": 2.0,
    "collision_zero_speed_threshold": 0.1,
    "route_min_length_m": None,
    "route_max_waypoints": None,
    "route_length_tolerance": 0.05,
    "reference_sample_spacing": 1.0,
    "reference_smoothing_window": 7,
    "reference_lane_margin": 0.35,
    "reference_max_centerline_offset": 1.25,
    "noise_lateral_std": 0.10,
    "noise_heading_std_deg": 1.0,
    "perception_delay_steps": 0,
    "perception_dropout_probability": 0.0,
    "perception_smoothing_alpha": 1.0,
    "lqr_q_ey": 3.4,
    "lqr_q_ey_dot": 1.30,
    "lqr_q_epsi": 7.2,
    "lqr_q_epsi_dot": 4.2,
    "lqr_r": 7.4,
    "lqr_kp_long": 0.6,
    "lqr_ki_long": 0.01,
    "lqr_kd_long": 0.06,
    "lqr_max_steer": 0.60,
    "lqr_max_steer_rate": 0.22,
    "lqr_derivative_alpha": 0.20,
    "lqr_curvature_alpha": 0.60,
    "lqr_feedforward_gain": 1.0,
    "lqr_curvature_preview_horizon": 12,
    "lqr_curvature_preview_blend": 0.40,
    "mpc_horizon": 20,
    "mpc_q_y": 14.0,
    "mpc_q_psi": 22.0,
    "mpc_r_steer": 1.0,
    "mpc_r_steer_rate": 0.9,
    "mpc_kp_long": 0.6,
    "mpc_ki_long": 0.01,
    "mpc_kd_long": 0.06,
    "mpc_max_steer": 0.65,
    "mpc_max_steer_rate": 0.08,
    "mpc_curvature_step_limit": 0.02,
    "mpc_max_lateral_accel": 6.0,
    "mpc_min_dynamic_steer_limit": 0.24,
    "mpc_cornering_stiffness_scale": 1.0,
    "mpc_min_horizon": 10,
    "mpc_adaptive_horizon_enabled": False,
    "mpc_model_type": "kinematic",
    "mpc_derivative_alpha": 0.25,
    "mpc_event_trigger_curvature": 0.008,
    "mpc_curvature_filter_alpha": 0.20,
    "mpc_curvature_feedforward_gain": 1.0,
    "mpc_small_error_steer_deadband_enabled": False,
    "mpc_small_error_lateral_threshold": 0.08,
    "mpc_small_error_heading_threshold": 0.8,
    "mpc_small_error_steer_hold_delta": 0.006,
    "mpc_small_error_current_curvature_threshold": 0.010,
    "debug_mpc_stability": False,
    "pid_lat_kp": 0.72,
    "pid_lat_ki": 0.005,
    "pid_lat_kd": 0.38,
    "pid_long_kp": 0.45,
    "pid_long_ki": 0.01,
    "pid_long_kd": 0.10,
    "pid_max_throttle": 1.0,
    "pid_max_brake": 0.28,
    "pid_max_steer": 0.65,
    "pid_max_steer_rate": 0.10,
    "pid_curvature_feedforward_gain": 0.90,
    "pid_curvature_preview_horizon": 10,
    "pid_curvature_preview_blend": 0.55,
}

CLI_ARGUMENTS = (
    (("--spawn-index",), {"type": int, "default": None, "help": "Optional fixed spawn point index for repeatable tests."}),
    (("--destination-index",), {"type": int, "default": None, "help": "Optional fixed destination spawn point index for repeatable tests."}),
    (("--target-speed",), {"type": float, "default": DEFAULTS["target_speed"], "help": "Target speed in km/h."}),
    (("--planner-mode",), {"choices": ("legacy", "frenet"), "default": DEFAULTS["planner_mode"], "help": "Reference planner used before all controller laps."}),
    (("--planner-fallback",), {"choices": ("legacy", "error"), "default": DEFAULTS["planner_fallback"], "help": "Expected Frenet failure policy: use legacy for normal runs or error for strict comparisons."}),
    (("--planner-validation-spacing",), {"type": float, "default": DEFAULTS["planner_validation_spacing"], "help": "Frenet constraint-validation spacing in meters."}),
    (("--planner-vehicle-half-width",), {"type": float, "default": DEFAULTS["planner_vehicle_half_width"], "help": "Vehicle half-width used for lane-footprint validation in meters."}),
    (("--planner-lane-margin",), {"type": float, "default": DEFAULTS["planner_lane_margin"], "help": "Lane-boundary safety margin used by the Frenet planner in meters."}),
    (("--planner-topology-beam-width",), {"type": int, "default": DEFAULTS["planner_topology_beam_width"], "help": "Beam width for topology-route branch search."}),
    (("--planner-lateral-beam-width",), {"type": int, "default": DEFAULTS["planner_lateral_beam_width"], "help": "Beam width for Frenet lateral candidates."}),
    (("--planner-candidate-cap",), {"type": int, "default": DEFAULTS["planner_candidate_cap"], "help": "Maximum Frenet candidates evaluated."}),
    (("--planner-deadline",), {"type": float, "default": DEFAULTS["planner_deadline"], "help": "Offline Frenet planning deadline in seconds."}),
    (("--planner-max-curvature",), {"type": float, "default": DEFAULTS["planner_max_curvature"], "help": "Maximum absolute reference curvature in 1/m."}),
    (("--planner-max-curvature-rate",), {"type": float, "default": DEFAULTS["planner_max_curvature_rate"], "help": "Maximum absolute reference curvature rate in 1/m^2."}),
    (("--planner-max-lateral-accel",), {"type": float, "default": DEFAULTS["planner_max_lateral_accel"], "help": "Controller-neutral lateral-acceleration cap in m/s^2."}),
    (("--planner-max-lateral-jerk",), {"type": float, "default": DEFAULTS["planner_max_lateral_jerk"], "help": "Controller-neutral lateral-jerk cap in m/s^3."}),
    (("--tracker-max-rollback",), {"type": float, "default": DEFAULTS["tracker_max_rollback"], "help": "Maximum recovery rollback along the route in meters."}),
    (("--tracker-hold-steps",), {"type": int, "default": DEFAULTS["tracker_hold_steps"], "help": "Invalid-projection cycles held before terminating a lap."}),
    (("--speed-planner-mode",), {"choices": ("off", "adaptive"), "default": DEFAULTS["speed_planner_mode"], "help": "Use off for fixed-speed controller-only tests, or adaptive for integrated high-speed safety tests."}),
    (("--speed-planner-limit-profile",), {"choices": ("global", "controller"), "default": DEFAULTS["speed_planner_limit_profile"], "help": "Use global for identical speed-planner limits, or controller for PID/LQR/MPC-specific limits."}),
    (("--seed",), {"type": int, "default": None, "help": "Optional random seed used to reproduce a run."}),
    (("--carla-host",), {"default": DEFAULTS["carla_host"], "help": "CARLA server host."}),
    (("--carla-port",), {"type": int, "default": DEFAULTS["carla_port"], "help": "CARLA RPC port."}),
    (("--carla-timeout",), {"type": float, "default": DEFAULTS["carla_timeout"], "help": "CARLA client timeout in seconds."}),
    (("--route-resolution",), {"type": float, "default": DEFAULTS["route_resolution"], "help": "Global route waypoint spacing in meters."}),
    (("--look-ahead",), {"type": float, "default": DEFAULTS["look_ahead"], "help": "Base look-ahead distance in meters."}),
    (("--speed-planner-min-turn-speed",), {"type": float, "default": DEFAULTS["speed_planner_min_turn_speed"], "help": "Minimum planned speed in km/h for tight turns."}),
    (("--speed-planner-recovery-min-speed",), {"type": float, "default": DEFAULTS["speed_planner_recovery_min_speed"], "help": "Minimum planned speed in km/h for severe lateral or heading error recovery."}),
    (("--speed-planner-max-lateral-accel",), {"type": float, "default": DEFAULTS["speed_planner_max_lateral_accel"], "help": "Maximum lateral acceleration in m/s^2 used by curvature speed planning."}),
    (("--speed-planner-max-accel",), {"type": float, "default": DEFAULTS["speed_planner_max_accel"], "help": "Maximum planned target-speed increase in m/s^2."}),
    (("--speed-planner-max-decel",), {"type": float, "default": DEFAULTS["speed_planner_max_decel"], "help": "Maximum planned target-speed decrease in m/s^2."}),
    (("--speed-planner-lateral-error-warning",), {"type": float, "default": DEFAULTS["speed_planner_lateral_error_warning"], "help": "Lateral tracking error in meters where protective speed reduction starts."}),
    (("--speed-planner-lateral-error-critical",), {"type": float, "default": DEFAULTS["speed_planner_lateral_error_critical"], "help": "Lateral tracking error in meters where protective speed reduction reaches its minimum."}),
    (("--speed-planner-heading-error-warning",), {"type": float, "default": DEFAULTS["speed_planner_heading_error_warning"], "help": "Heading error in degrees where protective speed reduction starts."}),
    (("--speed-planner-heading-error-critical",), {"type": float, "default": DEFAULTS["speed_planner_heading_error_critical"], "help": "Heading error in degrees where protective speed reduction reaches its minimum."}),
    (("--speed-planner-lateral-error-rate-warning",), {"type": float, "default": DEFAULTS["speed_planner_lateral_error_rate_warning"], "help": "Lateral tracking error growth rate in m/s where protective speed reduction starts."}),
    (("--speed-planner-lateral-error-rate-critical",), {"type": float, "default": DEFAULTS["speed_planner_lateral_error_rate_critical"], "help": "Lateral tracking error growth rate in m/s where protective speed reduction reaches its minimum."}),
    (("--speed-planner-heading-error-rate-warning",), {"type": float, "default": DEFAULTS["speed_planner_heading_error_rate_warning"], "help": "Heading error growth rate in deg/s where protective speed reduction starts."}),
    (("--speed-planner-heading-error-rate-critical",), {"type": float, "default": DEFAULTS["speed_planner_heading_error_rate_critical"], "help": "Heading error growth rate in deg/s where protective speed reduction reaches its minimum."}),
    (("--speed-planner-lateral-error-rate-activation",), {"type": float, "default": DEFAULTS["speed_planner_lateral_error_rate_activation"], "help": "Minimum lateral error in meters before lateral-error-rate slowdown can trigger."}),
    (("--speed-planner-heading-error-rate-activation",), {"type": float, "default": DEFAULTS["speed_planner_heading_error_rate_activation"], "help": "Minimum heading error in degrees before heading-error-rate slowdown can trigger."}),
    (("--speed-planner-error-rate-alpha",), {"type": float, "default": DEFAULTS["speed_planner_error_rate_alpha"], "help": "Low-pass blend factor for speed-planner tracking-error growth rates."}),
    (("--speed-planner-recovery-hold-steps",), {"type": int, "default": DEFAULTS["speed_planner_recovery_hold_steps"], "help": "Control steps to keep protective recovery active after risk clears."}),
    (("--speed-planner-entry-max-speed",), {"type": float, "default": DEFAULTS["speed_planner_entry_max_speed"], "help": "Maximum planned speed in km/h when entering a detected curve at high target speed."}),
    (("--speed-planner-entry-curvature-threshold",), {"type": float, "default": DEFAULTS["speed_planner_entry_curvature_threshold"], "help": "Preview curvature threshold that activates the entry-corner speed cap."}),
    (("--speed-planner-entry-full-cap-curvature",), {"type": float, "default": DEFAULTS["speed_planner_entry_full_cap_curvature"], "help": "Preview curvature where the entry-corner cap reaches speed-planner-entry-max-speed."}),
    (("--speed-planner-emergency-turn-speed",), {"type": float, "default": DEFAULTS["speed_planner_emergency_turn_speed"], "help": "Lowest planned speed in km/h allowed for very sharp previewed curves."}),
    (("--speed-planner-emergency-curvature-threshold",), {"type": float, "default": DEFAULTS["speed_planner_emergency_curvature_threshold"], "help": "Preview curvature threshold where the very-sharp-curve speed floor starts dropping."}),
    (("--speed-planner-emergency-full-cap-curvature",), {"type": float, "default": DEFAULTS["speed_planner_emergency_full_cap_curvature"], "help": "Preview curvature where the very-sharp-curve speed floor reaches speed-planner-emergency-turn-speed."}),
    (("--collision-zero-speed-timeout",), {"type": float, "default": DEFAULTS["collision_zero_speed_timeout"], "help": "Terminate the current controller after a collision if speed stays near zero for this many seconds."}),
    (("--collision-zero-speed-threshold",), {"type": float, "default": DEFAULTS["collision_zero_speed_threshold"], "help": "Speed threshold in m/s used to treat the vehicle as stopped after a collision."}),
    (("--route-min-length-m",), {"type": float, "default": DEFAULTS["route_min_length_m"], "help": "Minimum route length in meters before the loop can end. Omit for speed-adaptive length."}),
    (("--route-max-waypoints",), {"type": int, "default": DEFAULTS["route_max_waypoints"], "help": "Maximum number of waypoints to follow when building the route. Omit for speed-adaptive capacity."}),
    (("--route-length-tolerance",), {"type": float, "default": DEFAULTS["route_length_tolerance"], "help": "Allowed route-length deviation ratio when selecting a shaped route."}),
    (("--reference-sample-spacing",), {"type": float, "default": DEFAULTS["reference_sample_spacing"], "help": "Spacing in meters for the smoothed lane-bounded reference path."}),
    (("--reference-smoothing-window",), {"type": int, "default": DEFAULTS["reference_smoothing_window"], "help": "Odd moving-window size used to smooth the route centerline into a reference path."}),
    (("--reference-lane-margin",), {"type": float, "default": DEFAULTS["reference_lane_margin"], "help": "Minimum lane-boundary clearance in meters retained when smoothing the reference path."}),
    (("--reference-max-centerline-offset",), {"type": float, "default": DEFAULTS["reference_max_centerline_offset"], "help": "Maximum allowed reference-path offset from the geometric lane centerline in meters."}),
    (("--noise-lateral-std",), {"type": float, "default": DEFAULTS["noise_lateral_std"], "help": "Standard deviation of lateral-error noise for noisy_ground_truth."}),
    (("--noise-heading-std-deg",), {"type": float, "default": DEFAULTS["noise_heading_std_deg"], "help": "Standard deviation of heading-error noise in degrees for noisy_ground_truth."}),
    (("--perception-delay-steps",), {"type": int, "default": DEFAULTS["perception_delay_steps"], "help": "Number of control steps to delay noisy/perception-proxy tracking errors."}),
    (("--perception-dropout-probability",), {"type": float, "default": DEFAULTS["perception_dropout_probability"], "help": "Probability of reusing the previous noisy/perception-proxy tracking error sample."}),
    (("--perception-smoothing-alpha",), {"type": float, "default": DEFAULTS["perception_smoothing_alpha"], "help": "Blend factor for noisy/perception-proxy tracking errors; 1.0 disables smoothing."}),
    (("--lqr-q-ey",), {"type": float, "default": DEFAULTS["lqr_q_ey"], "help": "LQR lateral error weight."}),
    (("--lqr-q-ey-dot",), {"type": float, "default": DEFAULTS["lqr_q_ey_dot"], "help": "LQR lateral error derivative weight."}),
    (("--lqr-q-epsi",), {"type": float, "default": DEFAULTS["lqr_q_epsi"], "help": "LQR heading error weight."}),
    (("--lqr-q-epsi-dot",), {"type": float, "default": DEFAULTS["lqr_q_epsi_dot"], "help": "LQR heading error derivative weight."}),
    (("--lqr-r",), {"type": float, "default": DEFAULTS["lqr_r"], "help": "LQR steering effort weight."}),
    (("--lqr-kp-long",), {"type": float, "default": DEFAULTS["lqr_kp_long"], "help": "LQR controller longitudinal P gain."}),
    (("--lqr-ki-long",), {"type": float, "default": DEFAULTS["lqr_ki_long"], "help": "LQR controller longitudinal I gain."}),
    (("--lqr-kd-long",), {"type": float, "default": DEFAULTS["lqr_kd_long"], "help": "LQR controller longitudinal D gain."}),
    (("--lqr-max-steer",), {"type": float, "default": DEFAULTS["lqr_max_steer"], "help": "Maximum LQR steering command."}),
    (("--lqr-max-steer-rate",), {"type": float, "default": DEFAULTS["lqr_max_steer_rate"], "help": "Maximum LQR steering change per control step."}),
    (("--lqr-derivative-alpha",), {"type": float, "default": DEFAULTS["lqr_derivative_alpha"], "help": "Low-pass blend factor for LQR error derivative states."}),
    (("--lqr-curvature-alpha",), {"type": float, "default": DEFAULTS["lqr_curvature_alpha"], "help": "Low-pass blend factor for LQR curvature feedforward."}),
    (("--lqr-feedforward-gain",), {"type": float, "default": DEFAULTS["lqr_feedforward_gain"], "help": "Gain applied to LQR bicycle-model curvature feedforward."}),
    (("--lqr-curvature-preview-horizon",), {"type": int, "default": DEFAULTS["lqr_curvature_preview_horizon"], "help": "Number of speed-scaled curvature samples used by LQR feedforward preview."}),
    (("--lqr-curvature-preview-blend",), {"type": float, "default": DEFAULTS["lqr_curvature_preview_blend"], "help": "Blend from current curvature toward the strongest near-preview curvature for LQR feedforward."}),
    (("--mpc-horizon",), {"type": int, "default": DEFAULTS["mpc_horizon"], "help": "MPC prediction horizon in control steps."}),
    (("--mpc-q-y",), {"type": float, "default": DEFAULTS["mpc_q_y"], "help": "MPC lateral error weight."}),
    (("--mpc-q-psi",), {"type": float, "default": DEFAULTS["mpc_q_psi"], "help": "MPC heading error weight."}),
    (("--mpc-r-steer",), {"type": float, "default": DEFAULTS["mpc_r_steer"], "help": "MPC steering effort weight."}),
    (("--mpc-r-steer-rate",), {"type": float, "default": DEFAULTS["mpc_r_steer_rate"], "help": "MPC steering-rate effort weight."}),
    (("--mpc-kp-long",), {"type": float, "default": DEFAULTS["mpc_kp_long"], "help": "MPC controller longitudinal P gain."}),
    (("--mpc-ki-long",), {"type": float, "default": DEFAULTS["mpc_ki_long"], "help": "MPC controller longitudinal I gain."}),
    (("--mpc-kd-long",), {"type": float, "default": DEFAULTS["mpc_kd_long"], "help": "MPC controller longitudinal D gain."}),
    (("--mpc-max-steer",), {"type": float, "default": DEFAULTS["mpc_max_steer"], "help": "Maximum MPC steering command."}),
    (("--mpc-max-steer-rate",), {"type": float, "default": DEFAULTS["mpc_max_steer_rate"], "help": "Maximum MPC steering change per control step."}),
    (("--mpc-curvature-step-limit",), {"type": float, "default": DEFAULTS["mpc_curvature_step_limit"], "help": "Maximum curvature change allowed between adjacent MPC preview samples."}),
    (("--mpc-max-lateral-accel",), {"type": float, "default": DEFAULTS["mpc_max_lateral_accel"], "help": "Approximate lateral-acceleration limit in m/s^2 for MPC dynamic steering bounds."}),
    (("--mpc-min-dynamic-steer-limit",), {"type": float, "default": DEFAULTS["mpc_min_dynamic_steer_limit"], "help": "Minimum steering bound retained when MPC applies speed-based dynamic steering limits."}),
    (("--mpc-cornering-stiffness-scale",), {"type": float, "default": DEFAULTS["mpc_cornering_stiffness_scale"], "help": "Multiplier applied to MPC dynamic bicycle cornering stiffness terms."}),
    (("--mpc-min-horizon",), {"type": int, "default": DEFAULTS["mpc_min_horizon"], "help": "Shortest MPC horizon used when event risk is low."}),
    (("--mpc-enable-adaptive-horizon",), {"dest": "mpc_adaptive_horizon_enabled", "action": "store_true", "default": DEFAULTS["mpc_adaptive_horizon_enabled"], "help": "Enable MPC horizon shortening/extension based on speed and curve-entry risk."}),
    (("--mpc-model-type",), {"choices": ("dynamic_bicycle", "kinematic"), "default": DEFAULTS["mpc_model_type"], "help": "Prediction model used by the MPC controller."}),
    (("--mpc-derivative-alpha",), {"type": float, "default": DEFAULTS["mpc_derivative_alpha"], "help": "Low-pass blend factor for MPC dynamic-model lateral-velocity and yaw-rate states."}),
    (("--mpc-event-trigger-curvature",), {"type": float, "default": DEFAULTS["mpc_event_trigger_curvature"], "help": "Deprecated compatibility option; MPC now solves from the current state every control cycle."}),
    (("--mpc-curvature-filter-alpha",), {"type": float, "default": DEFAULTS["mpc_curvature_filter_alpha"], "help": "Frame-to-frame low-pass blend factor for MPC curvature preview."}),
    (("--mpc-curvature-feedforward-gain",), {"type": float, "default": DEFAULTS["mpc_curvature_feedforward_gain"], "help": "Gain applied to MPC curvature feedforward reference steering."}),
    (("--mpc-disable-small-error-steer-deadband",), {"dest": "mpc_small_error_steer_deadband_enabled", "action": "store_false", "default": DEFAULTS["mpc_small_error_steer_deadband_enabled"], "help": "Deprecated compatibility option; the MPC steering deadband is always disabled."}),
    (("--mpc-small-error-lateral-threshold",), {"type": float, "default": DEFAULTS["mpc_small_error_lateral_threshold"], "help": "Lateral-error threshold in meters for MPC small-error steering hold."}),
    (("--mpc-small-error-heading-threshold",), {"type": float, "default": DEFAULTS["mpc_small_error_heading_threshold"], "help": "Heading-error threshold in degrees for MPC small-error steering hold."}),
    (("--mpc-small-error-steer-hold-delta",), {"type": float, "default": DEFAULTS["mpc_small_error_steer_hold_delta"], "help": "Maximum steering delta held by MPC when lateral and heading errors are small."}),
    (("--mpc-small-error-current-curvature-threshold",), {"type": float, "default": DEFAULTS["mpc_small_error_current_curvature_threshold"], "help": "Current curvature threshold above which MPC small-error steering changes are released."}),
    (("--debug-mpc-stability",), {"action": "store_true", "default": DEFAULTS["debug_mpc_stability"], "help": "Print MPC stability diagnostics including profile, curvature, steering, and solve mode."}),
    (("--pid-lat-kp",), {"type": float, "default": DEFAULTS["pid_lat_kp"], "help": "PID lateral P gain."}),
    (("--pid-lat-ki",), {"type": float, "default": DEFAULTS["pid_lat_ki"], "help": "PID lateral I gain."}),
    (("--pid-lat-kd",), {"type": float, "default": DEFAULTS["pid_lat_kd"], "help": "PID lateral D gain."}),
    (("--pid-long-kp",), {"type": float, "default": DEFAULTS["pid_long_kp"], "help": "PID longitudinal P gain."}),
    (("--pid-long-ki",), {"type": float, "default": DEFAULTS["pid_long_ki"], "help": "PID longitudinal I gain."}),
    (("--pid-long-kd",), {"type": float, "default": DEFAULTS["pid_long_kd"], "help": "PID longitudinal D gain."}),
    (("--pid-max-throttle",), {"type": float, "default": DEFAULTS["pid_max_throttle"], "help": "Maximum PID throttle command."}),
    (("--pid-max-brake",), {"type": float, "default": DEFAULTS["pid_max_brake"], "help": "Maximum PID brake command."}),
)

LQR_LONGITUDINAL_PARAM_FIELDS = (
    "lqr_kp_long",
    "lqr_ki_long",
    "lqr_kd_long",
)

LQR_SUMMARY_PARAM_FIELDS = (
    "lqr_q_ey",
    "lqr_q_ey_dot",
    "lqr_q_epsi",
    "lqr_q_epsi_dot",
    "lqr_r",
    "lqr_max_steer",
    "lqr_max_steer_rate",
    "lqr_derivative_alpha",
    "lqr_curvature_alpha",
    "lqr_feedforward_gain",
    "lqr_curvature_preview_horizon",
    "lqr_curvature_preview_blend",
)

LQR_STEP_PARAM_FIELDS = (
    *LQR_SUMMARY_PARAM_FIELDS[:5],
    *LQR_LONGITUDINAL_PARAM_FIELDS,
    *LQR_SUMMARY_PARAM_FIELDS[5:],
)

MPC_PARAM_FIELDS = (
    "mpc_horizon",
    "mpc_q_y",
    "mpc_q_psi",
    "mpc_r_steer",
    "mpc_r_steer_rate",
    "mpc_kp_long",
    "mpc_ki_long",
    "mpc_kd_long",
    "mpc_max_steer",
    "mpc_max_steer_rate",
    "mpc_curvature_step_limit",
    "mpc_max_lateral_accel",
    "mpc_min_dynamic_steer_limit",
    "mpc_cornering_stiffness_scale",
    "mpc_min_horizon",
    "mpc_adaptive_horizon_enabled",
    "mpc_model_type",
    "mpc_derivative_alpha",
    "mpc_event_trigger_curvature",
    "mpc_curvature_filter_alpha",
    "mpc_curvature_feedforward_gain",
    "mpc_small_error_steer_deadband_enabled",
    "mpc_small_error_lateral_threshold",
    "mpc_small_error_heading_threshold",
    "mpc_small_error_steer_hold_delta",
    "mpc_small_error_current_curvature_threshold",
    "debug_mpc_stability",
)

PID_PARAM_FIELDS = (
    "pid_lat_kp",
    "pid_lat_ki",
    "pid_lat_kd",
    "pid_long_kp",
    "pid_long_ki",
    "pid_long_kd",
    "pid_max_throttle",
    "pid_max_brake",
)

STEP_CONTROLLER_PARAM_FIELDS = LQR_STEP_PARAM_FIELDS + MPC_PARAM_FIELDS + PID_PARAM_FIELDS
SUMMARY_CONTROLLER_PARAM_FIELDS = LQR_SUMMARY_PARAM_FIELDS + MPC_PARAM_FIELDS + PID_PARAM_FIELDS

SPEED_PLANNER_CONFIG_FIELDS = (
    ("mode", "speed_planner_mode"),
    ("limit_profile", "speed_planner_limit_profile"),
    ("min_turn_speed_kmh", "speed_planner_min_turn_speed"),
    ("recovery_min_speed_kmh", "speed_planner_recovery_min_speed"),
    ("max_lateral_accel", "speed_planner_max_lateral_accel"),
    ("max_accel", "speed_planner_max_accel"),
    ("max_decel", "speed_planner_max_decel"),
    ("lateral_error_warning", "speed_planner_lateral_error_warning"),
    ("lateral_error_critical", "speed_planner_lateral_error_critical"),
    ("heading_error_warning_deg", "speed_planner_heading_error_warning"),
    ("heading_error_critical_deg", "speed_planner_heading_error_critical"),
    ("lateral_error_rate_warning", "speed_planner_lateral_error_rate_warning"),
    ("lateral_error_rate_critical", "speed_planner_lateral_error_rate_critical"),
    ("heading_error_rate_warning_deg", "speed_planner_heading_error_rate_warning"),
    ("heading_error_rate_critical_deg", "speed_planner_heading_error_rate_critical"),
    ("lateral_error_rate_activation", "speed_planner_lateral_error_rate_activation"),
    ("heading_error_rate_activation_deg", "speed_planner_heading_error_rate_activation"),
    ("error_rate_filter_alpha", "speed_planner_error_rate_alpha"),
    ("recovery_hold_steps", "speed_planner_recovery_hold_steps"),
    ("entry_max_speed_kmh", "speed_planner_entry_max_speed"),
    ("entry_curvature_threshold", "speed_planner_entry_curvature_threshold"),
    ("entry_full_cap_curvature", "speed_planner_entry_full_cap_curvature"),
    ("emergency_turn_speed_kmh", "speed_planner_emergency_turn_speed"),
    ("emergency_curvature_threshold", "speed_planner_emergency_curvature_threshold"),
    ("emergency_full_cap_curvature", "speed_planner_emergency_full_cap_curvature"),
)

RUN_CONFIG_CONTROLLER_FIELDS = {
    "lqr": LQR_SUMMARY_PARAM_FIELDS,
    "mpc": MPC_PARAM_FIELDS,
    "pid": PID_PARAM_FIELDS,
}


def arg_value(args, name):
    return getattr(args, name, DEFAULTS.get(name))


def arg_values(args, field_names):
    return [arg_value(args, name) for name in field_names]


def args_dict(args, field_pairs):
    return {key: arg_value(args, attr) for key, attr in field_pairs}


def controller_args_dict(args, controller_name):
    prefix = f"{controller_name}_"
    config = {}
    for attr in RUN_CONFIG_CONTROLLER_FIELDS[controller_name]:
        key = attr[len(prefix):] if attr.startswith(prefix) else attr
        if key == "small_error_heading_threshold":
            key = f"{key}_deg"
        config[key] = arg_value(args, attr)
    return config
